### ISSUE TITLE
ext.conf file and static dir missing

### ISSUE THREAD

**Issue by jimydirektsaft** [sapristi/mopidy-mowecl#3]
On a fresh installation mopidy complains as follws:

```
mopidy        | ERROR    2020-08-11 08:40:38,939 [1:MainThread] mopidy.ext                                                                                      
mopidy        |   Setup of extension from entry point mowecl failed, ignoring extension.                                                                        
mopidy        | Traceback (most recent call last):                                                                                                              
mopidy        |   File "/usr/local/lib/python3.7/dist-packages/mopidy/ext.py", line 230, in load_extensions                                                     
mopidy        |     default_config = extension.get_default_config()                                                                                             
mopidy        |   File "/usr/local/lib/python3.7/dist-packages/mopidy_mowecl/__init__.py", line 32, in get_default_config                                       
mopidy        |     return config.read(pathlib.Path(__file__).parent / "ext.conf")                                                                              
mopidy        |   File "/usr/local/lib/python3.7/dist-packages/mopidy/config/__init__.py", line 100, in read                                                    
mopidy        |     return pathlib.Path(config_file).read_text(errors="surrogateescape")                                                                        
mopidy        |   File "/usr/lib/python3.7/pathlib.py", line 1199, in read_text                                                                                 
mopidy        |     with self.open(mode='r', encoding=encoding, errors=errors) as f:                                                                           
mopidy        |   File "/usr/lib/python3.7/pathlib.py", line 1186, in open                                                                                     
mopidy        |     opener=self._opener)                                                                                                                       
mopidy        |   File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener                                                                                  
mopidy        |     return self._accessor.open(self, flags, mode)                                                                                              
mopidy        | FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/mopidy_mowecl/ext.conf'
```

If I copy ext.conf by hand from git this error is gone but starting the web client throws this error:
```
mopidy        | ERROR    2020-08-11 08:54:52,430 [1:HttpServer] tornado.application                                                                            
mopidy        |   Uncaught exception GET /mowecl/ (172.16.254.54)
mopidy        | HTTPServerRequest(protocol='http', host='dietpi:6680', method='GET', uri='/mowecl/', version='HTTP/1.1', remote_ip='172.16.254.54')            
mopidy        | Traceback (most recent call last):
mopidy        |   File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 1701, in _execute                                                         
mopidy        |     result = method(*self.path_args, **self.path_kwargs)
mopidy        |   File "/usr/local/lib/python3.7/dist-packages/mopidy_mowecl/file_server.py", line 28, in get                                                  
mopidy        |     return self.render("index.html", title="Mowecl", **template_params)                                                                        
mopidy        |   File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 856, in render                                                            
mopidy        |     html = self.render_string(template_name, **kwargs)
mopidy        |   File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 1002, in render_string                                                    
mopidy        |     t = loader.load(template_name)
mopidy        |   File "/usr/local/lib/python3.7/dist-packages/tornado/template.py", line 445, in load                                                         
mopidy        |     self.templates[name] = self._create_template(name)
mopidy        |   File "/usr/local/lib/python3.7/dist-packages/tornado/template.py", line 476, in _create_template                                             
mopidy        |     with open(path, "rb") as f:
mopidy        | FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/mopidy_mowecl/static/index.html'               
mopidy        | ERROR    2020-08-11 08:54:52,434 [1:HttpServer] tornado.access
mopidy        |   500 GET /mowecl/ (172.16.254.54) 5.59ms
```

**Comment by sapristi** [comment]
Thanks for the report ! 
There seems to be a problem with the last release, I have deleted v0.3.8 from pypi (I'll upload a version again when I have fixed the issue.

In the meantime, you can install previous version of mowecl:
`pip3 install mopidy-mowecl==0.3.6`

**Comment by sapristi** [comment]
Ok I have finally uploaded v0.4.0 on pypi, which should not have any problem. Let me know how it goes !
Cheers,

**Comment by heartbleeded** [comment]
Still having the same problem.

pip 21.0.1 from /home/pi/.local/lib/python3.7/site-packages/pip (python 3.7)
Python 3.7.3

Installed Mowecl-0.4.2, and mopidy.ext and static dir are missing.

**Comment by sapristi** [comment]
Could you put the logs and your specific setup ?

**Comment by qqqqqqqqq9** [comment]
Hi, 
if I compare the download-sizes, it's seems obvious to me, that something went wrong during packaging. 

Mopidy-Mowecl-0.4.2.tar.gz (9.9 kB)	Source	None	Apr 3, 2021	
Mopidy-Mowecl-0.4.0.tar.gz (1.9 MB)	Source	None	Aug 25, 2020

**Comment by sapristi** [comment]
Hmm yes it seems my circle-ci setup was wrong. I uploaded version 0.4.3 on pypi which should solve the issue.
